### ISSUE TITLE
Csv overwriting

### ISSUE THREAD

**Issue by tallywiesenberg** [tellor-io/PySigner#37]
Is the csv in the repo in the gitignore? Just thinking about how to make a common database of successful transactions vs each reporter maintaining a separate database, or git problems where we're merging our databases. just thinking out loud

**Comment by oraclown** [comment]
csv of successful transactions is in the gitignore.

If we really want a shared database of successful transactions, then we can pull them from the contract address on polyscan or something similar.

**Comment by tallywiesenberg** [comment]
oh ok thanks for clearing this up
